### ISSUE TITLE
Keep original relations after transformation

### ISSUE THREAD

**Issue by aronnoordhoek** [pldn/LDWizard#128]
To circumvent some performance issues from federated queries we want to directly add geometry to a linked dataset. Therefore we made a transformation that takes a bag pand ID and gets its corresponding geometry. However, in the triples this replaces the original ID object with the resulting polygon. This does not happen in the enriched csv, as a new column is created.

![image](https://github.com/pldn/LDWizard/assets/58031261/6631d7fa-6110-4fc5-944b-35a44f5a5035)

It would be nice if there was a transformation configuration option where you keep original relations. Is this functionality already available or being worked on? The GeoDataWizard is still using ldwizard-old from what I can see so maybe I am missing something.

**Comment by philipperenzen** [comment]
Hi @aronnoordhoek, 

Would it be possible to share an example CSV file for this issue as a minimum working example? (Such as the "**Testset_spatialwizard_csv_correctie.csv**" file in the assets folder of GeoWizard)

Thank you!

**Comment by wouterbeek** [comment]
Notice that the behavior proposed and implemented in this issue results in the following output (example from geo to feature):

```turtle
_:b0 <https://schema.org/sameAs> "Point(5.9885077122575 51.19355309031)" .
_:b0 <https://schema.org/sameAs> "https://data.kkg.kadaster.nl/id/gebouw/0957100000260969" .
```

Notice that the point cannot be considered `sdo:sameAs` (but the KKG IRI can be considered `sdo:sameAs`).

Do we really want this feature in LD Wizard? Since it makes creating correct RDF more difficult.

**Comment by wouterbeek** [comment]
An alternative solution is to do what older version of LD Wizard did:
- Add the enriched data in a new CSV column (e.g. "BAG ID" and "BAG ID - enriched").
- Leave the original header out of the RDF file (e.g. `sdo:sameAs` and `ex:hasParcel` are added, but `{baseIri}/BAG%20ID` and `{baseIri}/Geometry` are not added.

**Comment by philipperenzen** [comment]
This was resolved in version 3, where the original implementation was improved upon:
* `keepOriginalValue` option added for `columnRefinement`
        * when argument `keepValue` is set to `true` - it will keep the original value in combination with the refined value (with` owl:sameAs` predicate) instead of overwriting it in the RDF data
        * when optional argument `customPredicateIRI` is specified, the default `owl:sameAs` predicate will be replaced with the `customPredicateIRI` string
