### ISSUE TITLE
Default property suggestion is too dominant

### ISSUE THREAD

**Issue by EnnoMeijers** [pldn/LDWizard#184]
When running the LDWizard-Erfgoed version based on UpdateToV4 branch there is a dominant behaviour in suggesting the default property name that disables the selection of one of any of the configured Schema.org properties.  After removing the last character of the default suggested property, it jumps back to the original URI. See screen capture below:

![ldwizard-property-suggestion](https://github.com/pldn/LDWizard/assets/8688107/ee65d009-549a-42f8-8ef8-a557f3edfc64)

**Comment by pietervaneverdingen** [comment]
@GerwinBosch, can you solve this? This is a blocking issue for deploying the latest version of the Heritage Wizard in production. Thanks!

**Comment by GerwinBosch** [comment]
I've got the Fix ready in #189, will have it code-reviewed tomorrow and I expect by lunch to have updated the version and the PR(s)
