### ISSUE TITLE
Sampling of rows in configure step

### ISSUE THREAD

**Issue by rlzijdeman** [pldn/LDWizard#22]
- please allow for random rows to be displayed (not the first x lines);
- allow for a 'randomize' button, that shows another random set of 10 lines of the csv file.
This would allow you to 'browse' through the data a bit more in order to make informed decisions re the properties

**Comment by philipperenzen** [comment]
Instead of a random record view, a paginated alternative has been proposed in the pull request - where the user can 'page' through the records, additionally, the user can select the number of records shown per page.
