### ISSUE TITLE
Auto-suggest datatype IRIs

### ISSUE THREAD

**Issue by rlzijdeman** [pldn/LDWizard#24]
# Observation

Setting the datatype IRI for columns (see pldn/LDWizard#20) requires knowledge on the side of the user as to which datatype IRIs could apply to a given column.  It would be better if the LD Wizard would already narrow down the list of datatype IRI to those that are actually supported by the data,

# Suggestion

Let's teach LD Wizard how to automatically detect the datatype IRI for some columns, e.g., columns that contain values of the format `YYYY-MM-DD` could be `xsd:date`, columns with only whole numbers could be `xsd:integer`.

# Prior work 

See <https://github.com/DHLab-nl/guess_xsd_type> for an existing auto-detection approach.

## To discuss

- What happens if there are multiple "correct" datatype IRIs?  Should there still be some user action involved (as is currently the case with the key column selector), or should LD Wizard make a selection for the user?

**Comment by philipperenzen** [comment]
Since this issue expands on #21, it will be closed and added to #21.
