### ISSUE TITLE
paste base url to property search keyword if no url is given

### ISSUE THREAD

**Issue by rlzijdeman** [pldn/LDWizard#31]
Hi,

when looking for properties, but unable to find a proper one, I'd expect that typing just a search term would generate a uri for me based on the base uri + /vocab/ .
Instead I'm asked to enter a url. 
<img width="932" alt="Screenshot 2021-02-03 at 21 58 48" src="https://user-images.githubusercontent.com/3480446/106809147-9dce2a00-666b-11eb-869b-1bd3753ff193.png">

**Comment by wouterbeek** [comment]
I think this is a duplicate of #23 .  @rlzijdeman Feel free to reopen if I was wrong...
