### ISSUE TITLE
Verbeterde support voor IRI's in brondata <NL>

### ISSUE THREAD

**Issue by kad-wenner** [pldn/LDWizard#36]
- Er lijkt geen manier te zijn om aan te duiden dat de data die je omzet een IRI betreft, zowel met de IRI Prefix Transformation als in een kolom zonder value refinement. Dit zorgt er dus ook voor dat data die al in de preprocessing (in Excel) is verrijkt tot een IRI als string wordt omgezet (en deshalve niet echt bruikbaar is om relaties te leggen met bestaande data).
- **RELATED:** Deze wens sluit ook aan bij de functionaliteit genoemd in pldn/LDWizard#35 om een data type te kunnen selecteren.  Voorstel is dan ook om dit door de gebruiker selecteerbaar te maken. 

**N.B.** Deze observaties zijn gedaan op basis van de Kadaster variant (de Geodatawizard) beschikbaar op https://labs.kadaster.nl/demonstrators/geodatawizard/. Gewenste functionaliteit hoort echter meer thuis bij de LDWizard core.

**Comment by wouterbeek** [comment]
This issue is only about being able to have a IRI in your tabular source data and use that as the subject IRI of some triples.

The ability to set a datatype IRI is a different feature that is handled in #35

An MWE could be constructed with the following source data:
```
id,label
https:://example.com/abc,abc
```

And the following target graph:
```ttl
<https://example.com/abc> rdfs:label "abc".
```

This feature was also requested by @ivozandhuis in https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard/issues/33

**Comment by philipperenzen** [comment]
This has been resolved in version 3.0.0: 
* within column refinements it can now be specified if a transformation should return an IRI or literal with `yieldsLiteral` or `yieldsIri`.

I added an example in the CONFIGURING.md ([see here](https://github.com/pldn/LDWizard/blob/main/CONFIGURING.md#:~:text=%7B%0A%20%20%20%20%20%20label%3A%20%22Example%3A%20return%20IRI%20from%20input%22%2C%0A%20%20%20%20%20%20type%3A%20%22single%22%2C%0A%20%20%20%20%20%20description%3A%20%22In%20this%20transformation%20the%20returned%20value%20is%20the%20original%20IRI%22%2C%0A%20%20%20%20%20%20transformation%3A%20async%20(term%3A%20string)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20%60%24%7Bterm%7D%60%3B%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20yieldsIri%3A%20true%0A%20%20%20%20%7D%2C)) on how to do this, where the `columnRefinement`'s `transformation` returns the IRI from the source data and adds it to the RDF data.

Please feel free to reopen this issue if it persists.
