### ISSUE TITLE
Select a predefined profile (SHACL shapes)

### ISSUE THREAD

**Issue by pietervaneverdingen** [pldn/LDWizard#59]
### User story

- [Who] As a user of the LD Wizard,
- [What] I want to be able to select a predefined profile (SHACL shapes),
- [Why] So that my usage of the LD Wizard is guided.

### Background

- LD Wizard currently allows a user to configure a transformation to linked data.
- There is currently no guidance as to which properties a user must and/or may use.
- Specific LD Wizard configurations are often domain-based.  In such domains there are often clear requirements as to which properties must and/or may be used.
- SHACL is a standardized language that allows the specification of properties that must and/or may be used, for example of a per-class basis.

### Acceptance criteria

- It is possible to configure one or more predefined profiles (SHACL shapes) as part of regular LD Wizard configuration.  Like other configuration options, this configuration can be added to the `config.ts` file.
- The ability for a user to select one of the predefined profiles (SHACL shapes) on the second LD Wizard GUI page ("Configure").  The selection is coupled with the class selection step (the class and its corresponding node shape are related through the ‘sh:targetClass’ property).
- A visual overview in the second LD Wizard GUI page ("Configure") of which properties *must be* configured and which properties *may be* configured, in order to adhere to the selected pattern.
  - Make sure to share a GUI design of how this will look before implementing.  The GUI impact may be large, so it is good to be on the same page before implementing this step.
- The ability to validate whether the configured transformation indeed follows the selected pattern.  Validation should be performed when the user moves from the second page ("Configure") to the third page ("Export").
  - If validation fails, the ability to go back to the second page ("Configure") to improve the configuration further, and the ability to go forward even though validation fails.

---

A [bounty](https://www.pldn.nl/wiki/Bounties_List) has been placed on this issue by [PLDN](https://www.pldn.nl) for €1250
 
[Click here to learn more](https://www.pldn.nl/wiki/Bounty_Procedures) if you're interested in claiming this bounty by resolving this issue.

**Comment by danielbeeke** [comment]
Here is a mockup of how I think it could look.

![mockup](https://user-images.githubusercontent.com/684215/217531898-1cdf098b-9376-4cbe-9c7a-d3652957586d.png)

Questions:

- When one or multiple SHACL shapes are configured would the user still be able to create a class which does not have a matching shape? Meaning it would be free form as it is currently. This could also be a configuration.. 'enforceShaclShape' could be a configuration boolean.
- In the description it says that we need to do validation. I propose to first implement it on the level of optional and required predicates. Then we can have a review. And then I could implement data types. I have not yet looked at how data types are enforced.

**Comment by danielbeeke** [comment]
[Screencast from 2023-02-08 17-30-39.webm](https://user-images.githubusercontent.com/684215/217592377-47eb1119-7a3d-418e-8cf5-79655584d984.webm)

The work is done in this branch:
https://github.com/danielbeeke/LDWizard/tree/shacl-integration

At a later stage I can do a screencast with audio and explanations. 

The basic logic of requiring certain fields works. But I think it can be made user friendly. One thought I have is changing the autocomplete dialog and adding the required / optional predicates there. What do you think?

**Comment by philipperenzen** [comment]
This feature was added in version 3.
