### ISSUE TITLE
Is this project still evolving?

### ISSUE THREAD

**Issue by vemonet** [pldn/LDWizard#7]
Hi @GerwinBosch @wouterbeek 

We have been playing around with LDWizard lately and found it really convenient for annotating CSV file (I like the approach that enable devs to easily define refinements that can be then easily used by people annotating)

We faced a few limitations and bugs that we fixed, and sent pull requests (we think it would be interesting for anyone using LDWizard imo as they are quite generic):
- https://github.com/netwerk-digitaal-erfgoed/LDWizard-Core/pull/49
- https://github.com/netwerk-digitaal-erfgoed/LDWizard-Core/pull/51

We have created issues in a few repositories related to the LDWizard, but did not get any feedback. And I noticed the latest version of LDWizard-Core has not changed since almost 1 year

So we are wondering if you are still working on this project and open to accept contributions?

Otherwise we will publish our new fork on npm (it's a bit unconvenient to clone and build our fork every time)

**Comment by wouterbeek** [comment]
This project is still going strong :-)  We just made the move from the [NDE](https://netwerkdigitaalerfgoed.nl/) Github, who is responsible for developing the first implementation of LD Wizard, to the [PLDN](https://www.pldn.nl/wiki/Platform_Linked_Data_Nederland) Github.  We have a WG that is coming up with Next Steps as we speak.

**Comment by wouterbeek** [comment]
Another update this this project is still moving forward.  Closing this issue accordingly...
